[package]
name = "screen-region-share"
version = "0.1.0"
edition = "2024"
description = "A window that captures and displays the screen region behind it"

[dependencies]
bevy = "0.15.3"
crossbeam-channel = "0.5.14"
xcap = "0.4.0"
