name: Release

on:
  release:
    types: [created]

# Add permissions block to fix "Resource not accessible by integration" error
permissions:
  contents: write

jobs:
  build-and-upload:
    name: Build and Upload for ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        arch: [x86_64, arm64]
        include:
          - os: windows-latest
            arch: x86_64
            artifact_name: screen-region-share.exe
            asset_name: screen-region-share-windows-amd64.exe
          - os: windows-latest
            arch: arm64
            artifact_name: screen-region-share.exe
            asset_name: screen-region-share-windows-arm64.exe
            target: aarch64-pc-windows-msvc
          - os: macos-latest
            arch: x86_64
            artifact_name: screen-region-share
            asset_name: screen-region-share-macos-x86_64
            target: x86_64-apple-darwin
          - os: macos-latest
            arch: arm64
            artifact_name: screen-region-share
            asset_name: screen-region-share-macos-arm64
            target: aarch64-apple-darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Build for release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release ${{ matrix.target && format('--target {0}', matrix.target) || '' }}

      - name: Prepare asset path
        id: prepare-asset
        shell: bash
        run: |
          if [ -n "${{ matrix.target }}" ]; then
            echo "::set-output name=asset_path::./target/${{ matrix.target }}/release/${{ matrix.artifact_name }}"
          else
            echo "::set-output name=asset_path::./target/release/${{ matrix.artifact_name }}"
          fi

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.prepare-asset.outputs.asset_path }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: application/octet-stream